server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/flower?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: true
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.flower.pojo
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug

dubbo:
  scan:
    basePackages: com.flower
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.198.131:2181?backup=192.168.198.131:2182,192.168.198.131:2183